// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapi.Context;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20230606205157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe28"),
                            Description = "",
                            Nombre = "Actividades pendientes",
                            Peso = 12
                        },
                        new
                        {
                            CategoriaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe30"),
                            Description = "",
                            Nombre = "Aprender Angular",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("webapi.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe10"),
                            CategoriaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe28"),
                            Description = "",
                            FechaCreacion = new DateTime(2023, 6, 6, 15, 51, 57, 306, DateTimeKind.Local).AddTicks(9404),
                            PrioridadTarea = 2,
                            Titulo = "Primeras Tareas"
                        },
                        new
                        {
                            TareaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe11"),
                            CategoriaId = new Guid("98c49e77-37f5-4b88-86c0-6e5a797ffe30"),
                            Description = "",
                            FechaCreacion = new DateTime(2023, 6, 6, 15, 51, 57, 306, DateTimeKind.Local).AddTicks(9417),
                            PrioridadTarea = 0,
                            Titulo = "Programacion"
                        });
                });

            modelBuilder.Entity("webapi.Models.Tarea", b =>
                {
                    b.HasOne("webapi.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("webapi.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
